spring:
  flyway:
    locations: classpath:db/migration
    url: jdbc:postgresql://localhost:5432/postgres
    user: hits
    password: hits
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: hits
    password: hits
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8191

path_to_csv_file: projects, comments, users